version: "3.7"

services:
  pizza_app:
    build: .
    ports:
      - "8090:8080"
    environment:
      - FLASK_APP=pizza_site.py
      - FLASK_ENV=development
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pizza_db
      MYSQL_USER: pizza-admin
      MYSQL_PASSWORD: pa55w0rd
    ports:
      - "3307:3306" # To avoid conflicts
